name: Build and Package 
on: [push, release]
 
jobs:
  package-for-mac:
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v4 
    
    - name: Set up Python 
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip 
        pip install pyinstaller 
        pip install -r requirements.txt  
 
    - name: PyInstaller打包 
      run: |
        pyinstaller --onefile src/baoguan_more_final.py  \
          --name "MyApp" \
          --distpath dist/mac \
          --hidden-import=你的隐式依赖包名（如有）  # 可选 
 
    - name: Upload artifact 
      uses: actions/upload-artifact@v3 
      with:
        name: mac-executable 
        path: dist/mac/MyApp 
